from typing import Any, Optional, Callable, Coroutine, Awaitable, List, Protocol
from twitchio.message import ChatMessage, Channel, User

class Context(Protocol):
    """commands.Context の必要最小限の抽象"""
    author: User
    message: ChatMessage
    channel: Channel

    async def send(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    async def reply(self, msg: str, *args: Any, **kwargs: Any) -> None: ...

def command(*, name: Optional[str] = ..., aliases: Optional[List[str]] = ...) -> Callable[[Callable[..., Any]], Any]: ...
def group(*, invoke_fallback: bool = ...) -> Callable[[Callable[..., Any]], Any]: ...

class Component:
    def __init__(self, bot: "AutoBot") -> None: ...
    @staticmethod
    def listener() -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    # allow defining commands inside component
    def command(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class AutoBot:
    """
    v3 AutoBot の最小シグネチャと主要属性（v3.1.0 想定）
    """
    client_id: str
    client_secret: str
    bot_id: str
    owner_id: Optional[str]
    prefix: str

    conduits: List[Any]  # will be Conduit instances at runtime

    def __init__(self, *, client_id: str, client_secret: str, bot_id: str, owner_id: Optional[str] = None, prefix: str = "!") -> None: ...
    async def setup_hook(self) -> None: ...
    async def event_ready(self) -> None: ...
    async def start(self, *, load_tokens: bool = True) -> None: ...
    async def add_token(self, token: str, refresh: str) -> Any: ...
    def get_channel(self, name: str) -> Optional[Channel]: ...
    async def handle_commands(self, message: ChatMessage) -> None: ...
    # other convenience methods
    async def join_channels(self, channels: List[str] | str) -> None: ...
